// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNLBjDVqYU4jZeEzThEUuKgQdXKvrVDQ',
    appId: '1:767534304057:web:2e243e0f858aa6a766b6e8',
    messagingSenderId: '767534304057',
    projectId: 'project-3-178e1',
    authDomain: 'project-3-178e1.firebaseapp.com',
    storageBucket: 'project-3-178e1.firebasestorage.app',
    measurementId: 'G-CN97DPMEPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9fy-13AueT1WUTYzp4_Gx8jKz04HpC-A',
    appId: '1:767534304057:android:a32bfd22ebc522b266b6e8',
    messagingSenderId: '767534304057',
    projectId: 'project-3-178e1',
    storageBucket: 'project-3-178e1.firebasestorage.app',
  );
}
